export const Navigation_Routes = {
  DASHBOARD: "/",
  MEETING: "/meeting",
  MEMBER: "/member",
  SETUP: "/setup",
  ORGANIZATION: "/setup/organization",
  UNIT: "/setup/unit",
  COMMITTEE: "/setup/committee",
  DESIGNATION: "/setup/designation",
  DEDUCTION: "/setup/deduction",
  BRANCH: "/setup/branch",
  CALENDAR: "/calendar",
  MEMBER_DETAILS: "/member/:id",
  MEETING_DETAILS: "/Meeting/:id",
};
